### ISSUE TITLE
Calculated DPS drops with Element

### ISSUE THREAD

**Issue by shanep2300** [LeftBased/Borderlands-Weapon-DPS-Calculator-JavaScript#2]
![chrome_2019-10-07_17-52-36](https://user-images.githubusercontent.com/16820289/66351380-73f7dc80-e92b-11e9-8165-9eb7cf919b32.jpg)
![chrome_2019-10-07_17-53-21](https://user-images.githubusercontent.com/16820289/66351382-73f7dc80-e92b-11e9-8418-5e13d61a9a57.jpg)

**Comment by LeftBased** [comment]
I will look into code and see if I can implement a fix. That should not occur.

**Comment by LeftBased** [comment]
I was able to replicate the issues I am going to be doing some testing with the current values and seeing what is going on it seems like it's using the incorrect formula.

**Comment by LeftBased** [comment]
Good news was able to fix that formula issue. I now discovered an additional issue that has to be fixed before releasing the hotfix. so I am getting closer to fixing the formula issues. it seems like there was a miscalculation in the formula. I went over it and tested it again. it's now recalling the proper values.

**Comment by LeftBased** [comment]
I have now fixed the issues. and will now be uploading the updated version with the applied hotfix.
